---
title: "Summary of EGAD00001008337 for Meta-Analysis"
author: "T. Schaetzl and M. Kohl"
date: "December 2022"
output:
  rmarkdown::html_document:
    toc: true
    theme: united
    highlight: tango
---


## Import preprocessed data

```{r}
exportData <- readRDS(file = "../rds/EGAD00001008337data.rds")
logCPM <- t(exportData[,21:ncol(exportData)])
```


## Extract ENSEMBL IDs

```{r}
ensemblIDs <- rownames(logCPM)
```


## Calculate mean of replicated ENSEMBL IDs

```{r}
IDs <- unique(ensemblIDs)
logCPM2 <- matrix(0,ncol = ncol(logCPM), nrow = length(IDs))
for(i in 1:length(IDs)){
  logCPM2[i,] <- colMeans(logCPM[ensemblIDs==IDs[i],, drop = FALSE], na.rm = TRUE)
}
rownames(logCPM2) <- IDs
```


## Determine sample size, mean, and SD per group

```{r}
library(MKomics)
res <- mod.t.test(x = logCPM2, group = exportData$group)
res$SD1 <- apply(logCPM2[,exportData$group == "CTRL"], 1, sd, na.rm = TRUE)
res$SD2 <- apply(logCPM2[,exportData$group == "FSHD"], 1, sd, na.rm = TRUE)
table(exportData$group)
res$n1 <- 24
res$n2 <- 37
names(res)[c(8,10:13)] <- c("mean of control", "SD of control", "SD of FSHD", 
                            "n of control", "n of FSHD")
```


## Export results

```{r}
res.EGA <- res
res.EGA$ENSEMBL <- IDs
save(res.EGA, file = "summary_EGAD00001008337.RData")
```


## Software information

```{r}
sessionInfo()
```
